### ISSUE TITLE
Issue with _integrand_Lee09_v2

### ISSUE THREAD

**Issue by samsonajohnson** [rpoleski/MulensModel#10]
https://github.com/rpoleski/MulensModel/blob/995f0abf33ee33cff35f5da324fa36276b9dff21/source/MulensModel/pointlens.py#L388

Hi Radek/Jennifer,

I was recently trying to use 'finite_source_LD_Lee09' and it gave me an error for 'invalid values for sqrt' in _integrand_Lee09_v2. I looked at 'values' (the array) and it had a shape of (90,1000). Here, all the final column entries are set to zero, but there were a number of first column values that were negative still. It looks like there is a check on the first row, but the ones I had that were still negative were scattered about the array. I made a quick fix by just setting all negative entries of the first column to zero to follow the behavior of the next conditionals:
>values[:,0][values[:,0]<0] = 0
That worked, but there was some logic on the next column too but mine worked after the above fix so I didn't do much else.

Here is the parameters I used that caused it to throw in case you want to recreate it. 

        ndays=22/24.
       te = 0.01
        t_0 = 0.
       params_ps = {'t_0': t_0, 'u_0': 0.00001, 't_E': te}
        params_fs = {**params_ps, 'rho': rho}
        model_fs1 = mm.Model(params_fs)
        t_1 = t_0 - ndays
        t_2 = t_0 + ndays                                                                                    
        model_fs1.set_magnification_methods([t_1, 'finite_source_LD_Lee09', t_2])
        mags = model_fs1.magnification(all_ts,gamma=0.2)

Feel free to follow-up with me. I hope all is well!

Best,
-Samson

**Comment by jenniferyee** [comment]
As of [v2.18.0](https://github.com/rpoleski/MulensModel/releases/tag/v2.18.0), possibly earlier, the following code is error-free, so this may have been resolved:

"""
import MulensModel as mm
import numpy as np

# assumed (not provided)
rho = 0.1

# Provided by user
ndays = 22 / 24.
te = 0.01
t_0 = 0.
params_ps = {'t_0': t_0, 'u_0': 0.00001, 't_E': te}
params_fs = {**params_ps, 'rho': rho}
model_fs1 = mm.Model(params_fs)
t_1 = t_0 - ndays
t_2 = t_0 + ndays
model_fs1.set_magnification_methods([t_1, 'finite_source_LD_Lee09', t_2])

all_ts = np.linspace(
    t_0 - 20 * model_fs1.parameters.t_star,
    t_0 + 20 * model_fs1.parameters.t_star,
    1000) # assumed.

mags = model_fs1.get_magnification(all_ts, gamma=0.2)
"""

@rpoleski Thoughts?
