### ISSUE TITLE
Can't install to Windows.

### ISSUE THREAD

**Issue by KingwithQueen** [rpoleski/MulensModel#121]
I have tried all installation methods. None of it works.

If I use `pip install MulensModel`, then I get 'cl.exe failed with exit code 2' . I have attached the complete terminal output in the file 'error print. txt'.
[error print.txt](https://github.com/rpoleski/MulensModel/files/13998520/error.print.txt)

If I use `Python setup. py install`, I will get the same result as `pip install MulensModel`.

If I use `PYTHONPATH`, I will get the result shown in the following figure. Prompt: I am unable to load VBBinaryLensingLibrary_ Wrapper. so, but obviously this file exists, as shown in the following figure.

<img width="1407" alt="explorer_B2XQgAnuF6" src="https://github.com/rpoleski/MulensModel/assets/74342066/99f064e1-5896-4810-a6a4-008e90d44642">

The system I am using is Windows 11 Professional Edition 22H2.

**Comment by rpoleski** [comment]
The first two fail because of definition of constants in `adaptive_contour.c` -> `error C2065: “M_LN2”`
The third works, but without very important library VBBL. I'm guessing there could be a warning in the output of the make command. If you don't use VBBL, then everything else should work.

I don't have experience with Windows, so it's hard for me to help. @justi or @ketozhang , can you help? 

@architecture281 has a similar problem recently.

**Comment by rpoleski** [comment]
You may try solutions from [this StackOverflow thread](https://stackoverflow.com/questions/26065359/m-pi-flagged-as-undeclared-identifier) or manually remove `M_*` numerical contants:

- in source/AdaptiveContouring/adaptive_contour.c four times
M_LN2 -> 0.693147180559945309417
- in source/AdaptiveContouring/binext_adap.c ones
M_PI -> 3.14159265358979323846

Please let me know what works or doesn't work. I'd like to change the code so that it works for other Windows users.

**Comment by ketozhang** [comment]
I've had the same issue with an old version of VBBL on MacOS. @rpoleski that solution is what I'd for the short term.

Those constants names are very prone to conflicting with existing standards. I'd suggest renaming them, perhaps adding prefix like `ADAPTIVE_CONTOURING_M_LN2`.

**Comment by rpoleski** [comment]
Can someone try that or just replacing with values indicated above and let us know what works?

**Comment by KingwithQueen** [comment]
> The first two fail because of definition of constants in `adaptive_contour.c` -> `error C2065: “M_LN2”` The third works, but without very important library VBBL. I'm guessing there could be a warning in the output of the make command. If you don't use VBBL, then everything else should work.
> 
> I don't have experience with Windows, so it's hard for me to help. @justi or @ketozhang , can you help?
> 
> @architecture281 has a similar problem recently.

Sorry for the late reply, I recompiled it. I compiled using `mingw32-make` to obtain the `process_ Begin: CreatProcess (NULL, uname,...) failed`, But the file can still be compiled. I'm not sure what `process_ Begin: CreatProcess (NULL, uname,...) failed` means. Also, I forgot to mention one thing. In Makefile, the compiler made a mistake. The cpp file requires the use of a g++compiler instead of gcc, while the c file uses the gcc compiler. I have attached the complete output of compiling the VBBL library.

process_begin: CreateProcess(NULL, uname, ...) failed.
mingw32-make: Makefile:9: pipe: No error
g++ -lm -Wl,-soname,VBBinaryLensingLibrary_wrapper -shared -o VBBinaryLensingLibrary_wrapper.exe VBBinaryLensingLibrary_wrapper.cpp -O2 -fPIC -lstdc++ VBBinaryLensingLibrary.o

**Comment by KingwithQueen** [comment]
> You may try solutions from [this StackOverflow thread](https://stackoverflow.com/questions/26065359/m-pi-flagged-as-undeclared-identifier) or manually remove `M_*` numerical contants:
> 
> * in source/AdaptiveContouring/adaptive_contour.c four times
>   M_LN2 -> 0.693147180559945309417
> * in source/AdaptiveContouring/binext_adap.c ones
>   M_PI -> 3.14159265358979323846
> 
> Please let me know what works or doesn't work. I'd like to change the code so that it works for other Windows users.

I found the answer in [Microsoft's official manual](https://learn.microsoft.com/en-us/cpp/c-runtime-library/math-constants?view=msvc-170&redirectedfrom=MSDN). When using variables defined in the `<math. h>` library, I need to add `#define _USE_MATH_DEFINES` above `#include<math. h>`
Therefore, I changed #include<math. h> to 
```
#define _USE_MATH_DEFINES
#include <math.h>
```
in `adaptive_contour.c` and `binext_adap.c` respectively.
Afterwards, the issue with `error C2065` was resolved.

However, when I recompiled, I encountered `LNK1181 again: cannot open input file'm. lib '`.
Based on my experience and research, as long as `<math. h>` is included on Windows, this library is available. Therefore, on Windows, `libraries=["m"],` can be directly deleted. After doing so, I corrected the mistake and it was resolved. 

Unfortunately, new errors occurred afterwards. I got `binext_adap.obj : error LNK2001: Unresolved external symbol sincos`. I checked `binext_adap.c,` it was found that the function `sincos` was used inside. I did not find it in the standard library, so I suppose it may not be a function in the standard library. But when I searched for this function on Google, I found it in [Linux Standard Base Core Specification 4.1](https://refspecs.linuxfoundation.org/LSB_4.1.0/LSB-Core-generic/LSB-Core-generic/baselib-sincos.html). I think it is possible that the `<math. h>` library on Linux defines this function, but it is not defined on Windows. I'm not sure how to modify the code, but it doesn't seem to assign the result to any variables, so maybe I can just delete it? I only have a very basic knowledge of C language. Please tell me how to modify this code, and I will continue to try installing it.

**Comment by rpoleski** [comment]
Replace

```c
#ifdef __APPLE__
        __sincos(alpha,&sa,&ca);
#else
    sincos(alpha,&sa,&ca);
#endif
```
with
```c
sa = sin(alpha)
ca = cos(alpha)
```
The results of `sincos()` are passed by reference.

Looking forward for the results.

**Comment by KingwithQueen** [comment]
> ```c
> sa = sin(alpha)
> ca = cos(alpha)
> ```

After correcting this error, MulensModel was successfully installed on Windows. I tested the example_ 2 and example_ 15, all can operate normally. Example_ 15 used the VBBL library, and I think this should indicate that the VBBL library can also be used normally.

Additionally, I noticed that the installation program did not copy the example and data folders to the installation directory. When I execute `examples_15_fitting.py` in any directory, the script will try to read the data in the installation directory. However, in the installation directory (Python311\Lib\site-packages\MulensModel-2.19.2-py3.11-win-amd64.egg\MulensModel\), there is only one file with the name data and a volume of 1KiB without a suffix. I suggest that during installation, the example and data should be automatically copied to the installation directory for easy testing.

**Comment by rpoleski** [comment]
I corrected the AC code, made a release of MM v2.20.0, and uploaded it to PyPI. Can someone please try to install MM on Windows using PyPI/pip? Maybe @jdeast ?

**Comment by rpoleski** [comment]
In #123 the user also needed to remove `libraries=["m"]` twice in `setup.py`. I don't know, if this is Windows or Visual Studio issue. If I know, then I can correct `setup.py`.

**Comment by KingwithQueen** [comment]
> In #123 the user also needed to remove `libraries=["m"]` twice in `setup.py`. I don't know, if this is Windows or Visual Studio issue. If I know, then I can correct `setup.py`.

This should be an issue with VS, but when I install on Windows, the program defaults to calling VS clxe. Even though I have correctly configured MinGW64. I tested on a new computer and if MinGW64 is configured and the latest VS is not installed, the installation will report an error and prompt to install the latest VS C/C++generation tool. Therefore, if the user does not modify setup.py on their own, VS can be used by default when installing on Windows. So, there's no need to distinguish whether the problem originates from Windows or VS, just install it on Windows and delete this code.

**Comment by rpoleski** [comment]
Ok, thanks for info. I've updated setup.py (commit 73151bf) and uploaded to pypi. I hope everything works now.

@KingwithQueen , I've also started #124 .
