### ISSUE TITLE
Issues installing on windows

### ISSUE THREAD

**Issue by edove07** [rpoleski/MulensModel#123]
Good evening,
I attempted to run the pip install MulensModel and am getting several errors.  I am using visual studio and everything is up to date with visual studio and python but I can not seem to resolve the errors. A friend of mine tried the same on their pc and got a similar error.

  **LINK : fatal error LNK1181: cannot open input file 'm.lib'
  error: command 'C:\\BuildTools\\VC\\Tools\\MSVC\\14.38.33130\\bin\\HostX86\\x64\\link.exe' failed with exit code 1181
  [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  **ERROR: Failed building wheel for MulensModel
ERROR: Could not build wheels for MulensModel, which is required to install pyproject.toml-based projects**
PM>** 

There also package would be ignored errors but I am not sure if they are relevant yet.

Thank you for your help. If you need more information, please let me know, and I will try to provide what is needed.
E

**Comment by rpoleski** [comment]
Please go to `setup.py`, remove lines 34 and 40, and try installing using this local setup.py.

The other solution I've found on the net:
-> Project Properties -> Configuration Properties -> Linker (General) -> Enable Incremental Linking -> "No (/INCREMENTAL:NO)"

Please let me know how they work.

**Comment by edove07** [comment]
Commenting out 34 and 40 seems to have resolved the issue. Thank you for your time.
E
