### ISSUE TITLE
DeprecationWarning from NumPy in test_Model.py

### ISSUE THREAD

**Issue by rapoliveira** [rpoleski/MulensModel#127]
The automated tests using NumPy >= v1.25 present this DeprecationWarning:

```
source/MulensModel/tests/test_Model.py::test_BLPS_shear_active
  /Users/raphael/postdoc/MulensModel_raphael/source/MulensModel/tests/test_Model.py:182: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
    assert not isclose(magnification, 4.691830781584699, abs_tol=1e-2)
```

The [release notes](https://numpy.org/doc/stable/release/1.25.0-notes.html) from NumPy explains the change, which is related to not treating arrays of size 1 as scalars anymore.

Changing `magnification` to `magnification[0]` in test_BLPS_shear_active() solves it. I will do it!

**Comment by rpoleski** [comment]
The above one is easy.
Though, I see you also changed `integrate.simps` to `integrate.simpson`. Did scipy just change the name of the function? If so, then do you know when?

**Comment by rpoleski** [comment]
The main part done in 62d83c1.

**Comment by rpoleski** [comment]
Please add an if statement that decides which function to use based on `scipy.__version__` and then this function is used.

**Comment by rapoliveira** [comment]
Done! Based on the discussion in commit  fe58801, I added a try-except block instead.
- I used `except AttributeError` instead of only `except` to avoid Flake8(E722) warning
- Small correction: `simps` was renamed to `simpson` in v1.7.0 documentation and will soon be disabled

**Comment by rpoleski** [comment]
Thanks.
Suggestion: never use bare except. Reason: the code cannot be killed by Ctrl-C etc.
