### ISSUE TITLE
Plotting models in fluxes

### ISSUE THREAD

**Issue by jenniferyee** [rpoleski/MulensModel#129]
Weirdly enough, model.plot_lc does not appear to have a phot_fmt keyword. The light curve can ONLY be plotted in MAGNITUDES. Sometimes, we might want to use fluxes, so we should enable that as an option. Requires various refactoring in other functions.

**Comment by rpoleski** [comment]
It calls `Model._get_lc()` which also returns magnitudes always. That one should be changed as well.

**Comment by rpoleski** [comment]
@jenniferyee do you suggest to add a keyword to `model.plot_lc` or add a function `model.plot_flux`?

**Comment by rpoleski** [comment]
@jenniferyee - it was solved by Raphael in [https://github.com/rpoleski/MulensModel/pull/131](https://github.com/rpoleski/MulensModel/pull/131)
