### ISSUE TITLE
Feature Request: Return plotted quantities

### ISSUE THREAD

**Issue by ketozhang** [rpoleski/MulensModel#13]
For the purpose of using our own plotting tools, fitting methods, or even simulating fake data can we have the various plotting functions return the quantities. 

* `plot_magnitification` -> `get_magnitification`
* `plot_lc` -> `get_lc`
* etc

Let me know if there is a way to doing this and I'm just lost. Otherwise, I'm willing to make a PR

**Comment by rpoleski** [comment]
- There already is `Model.magnification()`.
- No such function yet, but you can easily get it:
```
A = my_model.magnification(...)
(f_s, f_b) = my_model.get_ref_fluxes()
magnitudes = MM.Utils.get_mag_from_flux(f_s[0] * A + f_b)
```
You're right it would be better to add it as a separate function.
- There is also `Model.get_residuals()`.

Please note that soon (week timescale) we plan to release v2.0 and functions handling fluxes will change.

**Comment by ketozhang** [comment]
Wonderful, thank you! This solves it for me.

**Comment by rpoleski** [comment]
One comment - v2.0 is almost ready in `new_fit` branch. It will take longer than a week to merge it to `master` branch and release, but all the important changes are already done and we're mostly working on documentation.

**Comment by rpoleski** [comment]
Yes. Sympy is already included in the master branch and in the new_fit branch which soon will be merged to master and become v2.0.

**Comment by rpoleski** [comment]
Version 2.0 of MulensModel is released. It contains `Model.get_magnification` and `get_lc` will be added soon.

**Comment by rpoleski** [comment]
`get_lc` was added to `Model` class: [link](https://github.com/rpoleski/MulensModel/blob/99f7bc54d08bf4786627d230e6fb911a8cd1a8c6/source/MulensModel/model.py#L185)
