### ISSUE TITLE
issue with upload to PyPI

### ISSUE THREAD

**Issue by rpoleski** [rpoleski/MulensModel#133]
GIthub action that uploads to PyPI failed:

[https://github.com/rpoleski/MulensModel/actions/runs/8857835510](https://github.com/rpoleski/MulensModel/actions/runs/8857835510)

@ketozhang Can you help with that one?

**Comment by ketozhang** [comment]
Issue is not being able to build the wheel for Python 3.7 for MACOS. 3.7 has been long outdated. 

We have a choice to pursue trying a different method to build the 3.7 wheels or not. If we do not, existing 3.7 users could still use MulensModel, we just don't have wheels for them.

**Comment by rpoleski** [comment]
So changing:
```
cibw_build: [cp37-*, cp38-*, cp39-*, cp310-*, cp311-*]
```
->
```
cibw_build: [cp38-*, cp39-*, cp310-*, cp311-*]
```
should work?

**Comment by ketozhang** [comment]
Yep that works. I added a PR for this #134, since I notice in the future so you could've uploaded all the other wheels if you're  in a hurry to release.

**Comment by rpoleski** [comment]
Thanks! New version is already on PyPI.
