### ISSUE TITLE
Value Error: '<P' is not a valid PEP 3118 buffer format string

### ISSUE THREAD

**Issue by jenniferyee** [rpoleski/MulensModel#2]
This error appears when running example_01...py

It appears to be a problem with the latest version of numpy. Reverting to numpy 1.14.6 fixes it.

**Comment by rpoleski** [comment]
What was the error message? Did it say "ctypes" issue or "numpy" issue?

**Comment by jenniferyee** [comment]
numpy
--------------------------------------------------------------
Dr. Jennifer C. Yee

Office: P-341
Harvard-Smithsonian Center for Astrophysics
60 Garden St, MS-15
Cambridge, MA 02138
--------------------------------------------------------------

**Comment by rpoleski** [comment]
I've added some notes on this issue [here](https://github.com/rpoleski/MulensModel/blob/master/documents/macos_install.md).
