### ISSUE TITLE
Failed building wheel for MulensModel v2.6.0 during pip install

### ISSUE THREAD

**Issue by ketozhang** [rpoleski/MulensModel#22]
To reproduce,
```
$ pip install MulensModel==2.6.0

...

  source/VBBL/vbbl_wrapper.cpp:64:3: error: use of undeclared identifier 'mag'
    mag = VBBL.BinaryMag0(a, q, y1, y2);
    ^
  source/VBBL/vbbl_wrapper.cpp:66:29: error: use of undeclared identifier 'mag'; did you mean 'imag'?
    return Py_BuildValue("d", mag);
                              ^~~
                              imag
  source/VBBL/VBBinaryLensingLibrary.h:247:8: note: 'imag' declared here
  double imag(complex);
```

@rpoleski, this looks like it came from a recent commit: https://github.com/rpoleski/MulensModel/commit/8d2a56e181a43f8ba843a705dd039fa3539ccad7

**Comment by rpoleski** [comment]
[This commit](https://github.com/rpoleski/MulensModel/commit/88f6a19284bb03916e12ba5b2025c808e9469870) corrects it. I'll release v2.6.2.

I was testing the `PYTHONPATH` installation only because that's what I'm used to ;)

**Comment by ketozhang** [comment]
Thanks, that worked. Closing...
