### ISSUE TITLE
`get_magnification()` type checking is too constraining

### ISSUE THREAD

**Issue by ketozhang** [rpoleski/MulensModel#28]
In these lines, a type check is done to only allow a limited set of types:
https://github.com/rpoleski/MulensModel/blob/6836cbd646fbb02a252a15368f5db9b04b86cbbe/source/MulensModel/model.py#L1129-L1136

An example of unsupported type now is `pd.Series`.

In general type checking is heavily discouraged in Python to preserve "duck-typing". Usually numpy operations is very good at not needing their users to explicitly cast to ndarray. If you really need to use `np.asarray` or `np.asanyarray`.

**Comment by ketozhang** [comment]
Working on this issue and changing out the type checking on (possibly) multiple places.

**Comment by rpoleski** [comment]
It turn out that `np.atleast_1d()` should be used instead of `np.asarray()` because the user may provide float as an input. Corrected in 6488858
