### ISSUE TITLE
AttributeError: 'SatelliteSkyCoord' object has no attribute 'transform_to'

### ISSUE THREAD

**Issue by lisadang27** [rpoleski/MulensModel#3]
Hello, 
I am going through the example code to generate Figure #2 from Poleski & Yee 2018: https://arxiv.org/pdf/1803.01003.pdf
and am modifying it to plot the source trajectory 1) accounting for annual parallax and 2) as seen from Spitzer.
I get the following error when I try to plot the trajectory from Spitzer's perspective (it seems like the function transform_to is missing):
<img width="902" alt="screen shot 2019-03-07 at 7 23 27 pm" src="https://user-images.githubusercontent.com/17075772/54005523-a54ac880-410e-11e9-8235-67609c8d28cf.png">
<img width="844" alt="screen shot 2019-03-07 at 7 24 02 pm" src="https://user-images.githubusercontent.com/17075772/54005526-a976e600-410e-11e9-9289-4b44de6fc6c5.png">

**Comment by rpoleski** [comment]
Hi,

Thanks for pointing this out. There seems to be an inconsistency on my side - the input in plot_trajectory() has to be astropy's skycoord. You can get this by modifying line 43 to something like:

`model_sa_parallax.plot_trajectory(times=timestmp, label='satellite', satellite_skycoord=satellite.get_satellite_coords(timestmp))`

Note that I've added times=... and .get_satellite_coords(). If you don't add times=... than there is a default guess for the time range. The second change corrects the actual problem you encountered. Let me know if there are any other issues. I'll correct the MM code later as now I'm working on the problems with installing MM (see [this branch](https://github.com/rpoleski/MulensModel/tree/install) for improved install).

**Comment by lisadang27** [comment]
Ah, thank you for the help! That solved it!

**Comment by rpoleski** [comment]
Ok, simple solution is already coded: [commit](https://github.com/rpoleski/MulensModel/commit/405312d8f8ed1279ead446f86ceae06a110dcdec). Your original code should now work. I'll update documentation later.
