### ISSUE TITLE
MulensModel and multiprocessing

### ISSUE THREAD

**Issue by KKruszynska** [rpoleski/MulensModel#32]
Hi, I have been using MulensModel for a while now and today I realised that it would make my life easier, if I started using multiprocessing for fitting/exploring the parameters space with emcee package.

I followed an example prepared by the author of emcee [shown here](https://emcee.readthedocs.io/en/stable/tutorials/parallel/) (section about Multiprocessing).

So, it works fine with MulensModel, when I applied it to code like in [example_06](https://github.com/rpoleski/MulensModel/blob/master/examples/example_06_fit_parallax_EMCEE.py).

However, when I wanted to modify example_16 to work with multiprocessing, I ran into this error:
```
Traceback (most recent call last):
  File "../ulens_model_fit_multiproc.py", line 2592, in <module>
    ulens_model_fit.run_fit()
  File "../ulens_model_fit_multiproc.py", line 476, in run_fit
    self._run_fit(pooling=True)
  File "../ulens_model_fit_multiproc.py", line 1854, in _run_fit
    self._run_fit_EMCEE()
  File "../ulens_model_fit_multiproc.py", line 1865, in _run_fit_EMCEE
    self._fitting_parameters['n_steps'], progress=True)
  File "/home/kasia/anaconda3/envs/mulens_env/lib/python3.6/site-packages/emcee/ensemble.py", line 384, in run_mcmc
    for results in self.sample(initial_state, iterations=nsteps, **kwargs):
  File "/home/kasia/anaconda3/envs/mulens_env/lib/python3.6/site-packages/emcee/ensemble.py", line 285, in sample
    state.log_prob, state.blobs = self.compute_log_prob(state.coords)
  File "/home/kasia/anaconda3/envs/mulens_env/lib/python3.6/site-packages/emcee/ensemble.py", line 427, in compute_log_prob
    map_func(self.log_prob_fn, (p[i] for i in range(len(p))))
  File "/home/kasia/anaconda3/envs/mulens_env/lib/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/kasia/anaconda3/envs/mulens_env/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
  File "/home/kasia/anaconda3/envs/mulens_env/lib/python3.6/multiprocessing/pool.py", line 424, in _handle_tasks
    put(task)
  File "/home/kasia/anaconda3/envs/mulens_env/lib/python3.6/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/home/kasia/anaconda3/envs/mulens_env/lib/python3.6/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
TypeError: can't pickle dict_keys objects
```

Here is the snippet of the code it refers to:
![Screenshot from 2022-03-16 15-08-44](https://user-images.githubusercontent.com/36246703/158608929-7fc805bc-4276-4c9e-b579-26f2b70f1ce6.png)

And this is how I tried to setup the sampler:
![Screenshot from 2022-03-16 15-08-20](https://user-images.githubusercontent.com/36246703/158608804-446bf94c-5db9-4127-b0dc-ae95143b0ce4.png)

Does anyone know how to fix it or if there is a multiprocessing package that works well with MulensModel?

**Comment by rpoleski** [comment]
As a test - can you change example 6 to use a class for `ln_prob` and see if multiprocessing works in that case?

**Comment by rpoleski** [comment]
Almost solved - around line 415:

`self._fit_parameters_unsorted = self._starting_parameters.keys()`
===>>>
`self._fit_parameters_unsorted = list(self._starting_parameters.keys())`

and

`self._fit_parameters_unsorted = self._prior_limits.keys()`
===>>>
`self._fit_parameters_unsorted = list(self._prior_limits.keys())`

(Because dict_keys object cannot be pickled and list can.)
Also you cannot use `other_output` -> `models` settings if you want to use multiprocessing currently. 

To do list for me:
- apply above changes,
- allow multiprocessing from yaml file,
- handel other_output/models with multiprocessing.

**Comment by rpoleski** [comment]
I've started working on multiprocessing: [ex16_multiprocessing branch](https://github.com/rpoleski/MulensModel/tree/ex16_multiprocessing). I've checked it using PSPL model and it's not faster. Maybe it will be give speed-up only for more complicated models.

**Comment by KKruszynska** [comment]
I checked it just now... And there is a significant difference in speed.
Here is the output for "regular" approach in example 06:
`
> python example_06_fit_parallax_EMCEE.py 
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████| 1000/1000 [00:42<00:00, 23.80it/s]
Serial took 42.1 seconds
Fitted parameters:
2453630.36769 0.24325 0.23131
0.48907 0.01836 0.01756
93.48593 2.03602 2.12311
0.26966 0.03070 0.03248
0.10271 0.00779 0.00752

Smallest chi2 model:
2453630.3939780206 0.4885399120017645 93.73075180134451 0.2705439721081006 0.10165745666461598
946.7348719828399
`
And here is the same output for example 06 where I used multiprocessing:
`
python example_06_fit_parallax_EMCEE_mpl.py 
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████| 1000/1000 [00:25<00:00, 38.64it/s]
Multiprocessing took 26.0 seconds
Fitted parameters:
2453630.37761 0.23272 0.22983
0.49051 0.01949 0.01771
93.48531 2.20608 2.10952
0.27408 0.02853 0.03125
0.10280 0.00769 0.00769

Smallest chi2 model:
2453630.3636469557 0.48648386871042565 93.58889880004851 0.26461276382557886 0.10158070316258482
946.7380619878057
`

It took 1/3 time less to do the same calculations.
I used 80 walkers and 1000 steps for this example.

**Comment by KKruszynska** [comment]
I created this folder in my forked version of MulensModel:
https://github.com/KKruszynska/MulensModel/tree/master/examples/example_16_mpl

I am testing the code on a machine with 8 cores.
I set this up to remove automatic parallelization done by numpy see [comment in the first block here](https://emcee.readthedocs.io/en/stable/tutorials/parallel/)
```
import os

os.environ["OMP_NUM_THREADS"] = "1"
```

I will also post only the parts of output regarding the time exection.


1. Running ulens_model_fit_no_mpl.py -- this is the same code as the one in example 16 from the main branch, I just removed the automatic parallelization and I added a small comment about time used by running emcee sampler.

```
> python ulens_model_fit_no_mpl.py test_event.yaml 
100%|██████████████████████████████████████████████████████████████████████████| 1000/1000 [03:54<00:00,  4.26it/s]
Serial took 235.2 seconds
```

2. Running ulens_model_fit_mpl.py -- this is  the code used by example_16, but from the ex16_multiprocessing branch. Again, I removed automatic parallelization and I have added a comment about the time used up by the sampler.

```
> python ulens_model_fit_mpl.py test_event.yaml 
100%|██████████████████████████████████████████████████████████████████████████| 1000/1000 [04:08<00:00,  4.02it/s]
Multiprocessing took 249.1 seconds
```

3. Running ulens_simple_fit_emcee_mpl.py -- this is code I created hacking majority from example_06, adding some functions from example_10 (returning posteriors for fluxes) and one thing from example_16 (checking if flux of the blend is negative or not, if the user requires it). It's not a pretty thing to look at though and it's definitely not as flexible as example_16.

```
> python ulens_simple_fit_emcee_mpl.py 
100%|██████████████████████████████████████████████████████████████████████████| 1000/1000 [01:19<00:00, 12.56it/s]
Multiprocessing took 80.5 seconds
```

The last one is almost 3 times faster than the first and second version...

**Comment by rpoleski** [comment]
We have a case when a code that is based on simple functions is much faster than a code that does the same thing, but uses a huge class, which has many additional parameters. @ketozhang - do you know a tool that will help us find the reason of this difference?

**Comment by ketozhang** [comment]
@rpoleski You can try using a profiler. The standard package built-in to Python is CProfiler. 

See this SO, for GUI tools that visualizes CProfiler results:
https://stackoverflow.com/questions/3378953/is-there-a-visual-profiler-for-python

**Comment by rpoleski** [comment]
Thanks. I'll try it. I've used CProfiler, but somehow thought it's not useful for multiprocessing.

**Comment by ketozhang** [comment]
IMO it's extremely difficult to infer anything without using a GUI to visualize the data.
I have yet tried it with multiprocessing. Could be useful to look at the overhead cost. However I'd also investigate if you see the same behavior (i.e., one implementation is much faster than the other) with using a single process.

**Comment by rpoleski** [comment]
Kasia informed me privately that updating numpy has resulted in speeding-up the calculations on a single CPU. There is no need for multiprocessing right now.

**Comment by rpoleski** [comment]
@KKruszynska - is there a need for multiprocessing now. If not, then I'll close this issue.
