### ISSUE TITLE
AdaptiveContouring seg fault

### ISSUE THREAD

**Issue by rpoleski** [rpoleski/MulensModel#39]
Calling AC was causing problems from time to time and it was generally ignored. Recently @jenniferyee reported issues with a recent M1 mac processor and added `tests/check_architecture.py` in order to skip some tests. I had similar problems after recent linux upgrade. It seems that the more recent compilers got more strict in checking for seg faults.

J. Skowron and J. Suchecki (thanks guys!) found the culprit - `AdaptiveContouring/adaptive_contour.c` line 1488:

```C
if (reg->sub[0] != NULL) { /* 3-10-06 */
```

`reg->sub` is not allocated, hence, one cannot access `reg->sub[0]`.

For now, I've changed tests: 8a97ffd
I think we can consider removing `check_architecture.py`.

**Comment by jenniferyee** [comment]
It would be great to remove check_architecture.py . This test has a major drawback that it creates an additional package dependency for MM that is otherwise useless. I will check the new fix on my Mac and report back.

**Comment by rpoleski** [comment]
Note that there is also `test_BLPS_02_AC()` in `tests/test_Model.py` that depends on `check_architecture`. I agree on removing it ASAP.

**Comment by rpoleski** [comment]
If `test_BLPS_02_AC()` fails, then please specify exactly where, so that raw C code can be debugged.

**Comment by jenniferyee** [comment]
The AC tests pass now. I will remove check_architecture from the unit tests.
