### ISSUE TITLE
"Duplicated" entry in interpolation_table_b0b1_v1.dat

### ISSUE THREAD

**Issue by jenniferyee** [rpoleski/MulensModel#42]
In the b0b1 table, when the point density transitions from dz = 0.00005 to dz = 0.01, there are entries for both

z = 1.059999999999988951e+00
and 
z = 1.060000000000000053e+00

Technically, these numbers are not the same, so they don't raise any exceptions (e.g., a computer thinks they are monotonically increasing). However, I have noticed weird behavior near these values. Specifically, I used np.gradient() to calculate the derivatives of b0 and b1, and I get the wrong slope near this point. Removing the 1.06e+00 entry solved the problem. Because they are effectively the same number, I recommend removing this entry from the table to avoid any unexpected interpolation effects.

**Comment by rpoleski** [comment]
> I recommend removing this entry from the table

Agreed.

**Comment by jenniferyee** [comment]
Fixed in commit [https://github.com/rpoleski/MulensModel/commit/1e02d7c56b9c007856d4c16384ee2313886f5441](url)
