### ISSUE TITLE
Feature Request: Add xallarap effect

### ISSUE THREAD

**Issue by zhechenghu** [rpoleski/MulensModel#48]
Hi Radek/Jennifer,

Thank you for providing such a fantastic python package of microlensing modeling! I found it super helpful while learning microlensing.

I wonder whether it is possible to add the xallarap effect, which is an effect similar to microlensing parallax. A paper describes this effect clearly: 
[Miyazaki et al.](https://ui.adsabs.harvard.edu/abs/2021AJ....161...84M/abstract).

It would be appreciated so much if you could add this feature!

Cheers

**Comment by rpoleski** [comment]
Hi,

This is on our radar for a long time. We take great care when adding new features: there is always brainstorming on how to name functions, classes, parameters etc. This also happens slowly for xallarap. Though I cannot promise when it will be done. If you want to implement it yourself, then you have to modify Trajectory class.

I'm glad MM was useful for you.

**Comment by rpoleski** [comment]
I'm currently working on xallarap.
@Hu-Zhecheng If you're still interested in this feature, please contact me via email.

**Comment by rpoleski** [comment]
Xallarap is already part of the master branch. Closing.
