### ISSUE TITLE
Problem with running unit tests

### ISSUE THREAD

**Issue by twins111197** [rpoleski/MulensModel#5]
**From checks.py:**

System: posix Darwin 15.4.0
Python: 3.7.1 (default, Dec 14 2018, 13:28:58) 
[Clang 4.0.1 (tags/RELEASE_401/final)]
ctypes: 1.1.0
scipy: 1.1.0
numpy: 1.15.4
matplotlib: 3.0.2
astropy: 3.1
MulensModel: 1.10.0

**Warning:**

DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
    from collections import Mapping

-- Docs: https://docs.pytest.org/en/latest/warnings.html
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
================================================== 1 warnings, 1 error in 6.17 seconds =================================================

**Comment by rpoleski** [comment]
Hi,

Can you give some more information? The end of message indicates a warning and an error, but previous information is only about warning. MM does not directly import collections, so I don't see why it caused a warning. Does py.test work for some other package on the same machine?

Cheers,

Radek

**Comment by jenniferyee** [comment]
Working on this. Probably likely a path issue.

**Comment by rpoleski** [comment]
Turn out to be PYTHONPATH issue, not MM issue. Closing.
