### ISSUE TITLE
Masked 'bad' data has magnification issue with show_bad=True

### ISSUE THREAD

**Issue by rgkey** [rpoleski/MulensModel#52]
Hi!

I'm currently working with a lensing project that uses data with some epoch drop-outs due to seeing effecting faint stars.
The missing epochs are represented as a numpy.nan place holder in the magnitude, mag_err and time columns of a pandas dataframe. There's under 10  'bad' epochs and over 500 good measurements per star.

When I define a MulensData object, I use a single boolean array that has numpy.nan = True for a bad data mask. 

`bad_data = star['mag'].isna().values`
    
    data = mm.MulensData([objid['hjd'].to_numpy(dtype = np.float64), objid['mag'].to_numpy(dtype = np.float64), 
                          objid['magerr'].to_numpy(dtype = np.float64)], bad=bad_data)`

When I link a model to this dataset with Event() and then plot using:
`init_event.plot(data_ref=data, t_range=[data.time[0], data.time[-1]], legend=False)`
Everything works normally.

But when I plot with argument `show_bad=True`, an error message pops up and the magnification is calculated NaN everywhere.
<img width="1045" alt="Screen Shot 2022-07-12 at 12 37 34 pm" src="https://user-images.githubusercontent.com/45152240/178398865-9eb65788-69dc-4f01-9ce8-e82a42a674c9.png">

I'm unsure if I need to use `MulensData._set_plot_properties() ` to fix this issue, or perhaps because the bad epochs are NaN values in data.time() that the plot can't allocate an x-value to a bad epoch? Please let me know if I can clarify anything.

Cheers,
Renee

**Comment by rpoleski** [comment]
Hi Renee,

What are you trying to achive by calling `Event.plot()` with `show_bad=True`? The bad values are also NaN, so there is no way MM could plot them. Maybe the function you need is already implemented in MM, but it's hard for me to tell, if I don't know what you want.

Suggestion: from my experience it's better not to set time of missing epochs to NaN. Set mag and mag_err to NaN, but leave time as a float. This way it's easier to search the data.

**Comment by rgkey** [comment]
Thanks - I am working with pre-constructed data but I'll pass your suggestion on. 
I just wanted to clarify with you that this is a NaN plotting issue and not a magnification calculation error.

**Comment by rpoleski** [comment]
Yes. If you change time vector for these epochs, you will be able to calculate model magnification for these epochs.
