### ISSUE TITLE
Project logo

### ISSUE THREAD

**Issue by rpoleski** [rpoleski/MulensModel#54]
Can someone make a logo for MulensModel project? The image below is from @justi. I like the model and the lens. Something that could be changed is the peak of the model. If the peak looks like M, then it would look like planet anomaly. Or maybe somebody else can propose something completely different. 

![propozycja_1](https://user-images.githubusercontent.com/19961701/188862737-92c0baa8-4468-4b51-8a62-216262cd8fc1.png)

**Comment by spriya2236** [comment]
Hey, I will work on the logo and will send you draft of logo in sometime

**Comment by justi** [comment]
The second version:
![logo](https://user-images.githubusercontent.com/1021614/189539657-b3bf40ff-28ef-4ed9-9a79-4240875607f1.png)

**Comment by rpoleski** [comment]
Can we have 2 letters M? Maybe 2 different models going through these points (different colors in that case)?
@spriya2236 - I'm looking forward for what you propose!

**Comment by rpoleski** [comment]
I'm open to non black-and-white logo :) No colors prefered.
You can post a few possibilities if you have.

**Comment by ketozhang** [comment]
Can we get an M-shape out of caustic structure?

**Comment by rpoleski** [comment]
Actually, Jen added an example that plots two M. Blue is binary source model and magenta is binary lens model:

[https://github.com/rpoleski/MulensModel/blob/master/examples/example_23_logo_inspiration.py](https://github.com/rpoleski/MulensModel/blob/master/examples/example_23_logo_inspiration.py)

I hope it will be an inspiration for a logo.

![Screenshot from 2022-12-03 14-49-45](https://user-images.githubusercontent.com/19961701/205444386-fa840638-ccfa-449f-8f2e-86c8fdcb3a0a.png)

**Comment by rpoleski** [comment]
Solved - [ad5ee57](https://github.com/rpoleski/MulensModel/commit/ad5ee572eda82d1039283917f03957c7ae300fe5). 
Thanks to Grafi Grafomaniak!
