### ISSUE TITLE
Remove unused code in trajectory.py

### ISSUE THREAD

**Issue by rpoleski** [rpoleski/MulensModel#69]
In [`trajectory.py`](https://github.com/rpoleski/MulensModel/blob/master/source/MulensModel/trajectory.py) functions `_annual_parallax_trajectory()` and `_satellite_parallax_trajectory()` seems to be not used and not needed. Please verify it and remove the functions.

**Comment by jenniferyee** [comment]
Removed code. As a result, the 'delta' keyword in _project_delta() was no longer needed, so I removed that too. See commit 7c930c0.
