### ISSUE TITLE
Issue with setup.py Python2 & Python3

### ISSUE THREAD

**Issue by NumaKarolinski** [rpoleski/MulensModel#7]
I have tried to call `python setup.py install --user`, and I find that this doesn't work. I get the error:

Traceback (most recent call last):
  File "setup.py", line 14, in <module>
    files = glob.glob(os.path.join("data", "**", "*"), recursive=True)
TypeError: glob() got an unexpected keyword argument 'recursive'

From what I've found online, the argument 'recursive' only works for Python versions >= 3.5.

When I deleted the term `recursive = True` from this line, the installation worked fine.

**Comment by rpoleski** [comment]
Hi,

Yes, you're right - MM does not support python2. The support for python2 decreases in general (see e.g. astropy). We don't have resources to write code for both python2 and python3. So even though you were able to install, it's likely that something won't work. In particular examples will require "from \_\_future\_\_ import..." 

If there is a problem in python2 with something specific and simple, then I can correct it.
