### ISSUE TITLE
some ideas for a simple multi linear or polynomial regression analysis

### ISSUE THREAD

**Issue by eddiemorris135** [rpoleski/MulensModel#76]
Hi All,
As a novice in in machine learning with python and microlensing, I would like to conduct a basis machine learning analysis based on tutoral/example 1. 

Here I could vary the planetary parameters s, q, alpha and rho and then try to predict an outcome or dependent variable. 
Perhaps someone has an idea what output I could predict?

thanks!
Ed

**Comment by rpoleski** [comment]
Hi,

I'm glad you're interested in using MM for a new project. I would propose peak magnification as a dependent variable to predict. The other one that comes to my mind is the number of peaks in the magnification curve.
