### ISSUE TITLE
q > 1 is not allowed

### ISSUE THREAD

**Issue by jenniferyee** [rpoleski/MulensModel#84]
In wide binaries, there are two similar caustics. Technically, it is possible to probe source trajectories centered on either caustic. But in practice, it is often simpler to just use q --> 1/q to probe the other caustic because then t0 corresponds to the peak of the light curve.

Is there actually a limitation in the code algorithms that prevents q > 1? i.e., if we remove the raise Error for q > 1, will the code work as described above or will something weird happen?

**Comment by jenniferyee** [comment]
Simple test:

1. Write unit tests for the case q > 1.
2. Remove the condition new_q > 1 from Line 935 of modelparameters.py (q.setter method)

**Comment by rpoleski** [comment]
The above approach is fine, but not enough. We should also test trajectory plotting etc.

When we have wide-orbit planets and source approaches planet much closer than star , then I fit it using example 16 and re-parametrization of the model. Though, I had no case with alpha~90 or 270 deg (i.e., u_0 ~ s-1/s).

There may be cases when q~1 and in different models we would like to have different bodies to be more massive.

Definitely it's worth allowing q > 1 for the users perspective.

**Comment by rapoliveira** [comment]
Removing the condition q > 1 from lines 751 and 1095 of the current modelparameters.py, similar caustics can be obtained with `q -> 1/q` and `alpha -> alpha +/- 180`, as shown in the figure. I used the parameters from example01, with a slightly different value of s and with q = 0.25 and 4.

![FINAL_figs_combined](https://github.com/rpoleski/MulensModel/assets/29663898/31fc909d-d5ad-4e14-9330-080d2898f9fe)

Should I write unit tests and/or implement warnings in that case?

**Comment by rpoleski** [comment]
Great!
The next step would be to calculate magnification curves for both q=0.25 and q=4 case and make sure that they're the same. Assume rho = 0.001 and run it using each of four finite-source methods (for a list of methods see second page of `documents/magnification_methods.pdf`).
