### ISSUE TITLE
MacOS Installation problem. error: command 'gcc' failed with exit status 1

### ISSUE THREAD

**Issue by gj272** [rpoleski/MulensModel#9]
I have come across an error whilst trying to install MulensModel. 
<img width="1360" alt="Screenshot 2020-02-23 at 18 20 52" src="https://user-images.githubusercontent.com/60230067/75117771-58883680-566c-11ea-882e-79f9301d3d97.png">
So I tried most things on the stack threads, I have uninstalled the command line tools to reinstall them but I keep getting this #include <stdio.h> error. I do not know any C so any help or pointers would be greatly appreciated. :)

**Comment by rpoleski** [comment]
Hi,

It seems that there is basic problem with gcc compiler. The stdio.h is a standard C library.

First, have you tried things that fix only Xcode, not all the command line tools? For example, I've found suggestion to run `xcode-select --install`.

Second, can copy-paste whole output from the terminal? Maybe there is some other clue before.

Third, you can go to `MulensModel/source/AdaptiveContouring/` and run `make`. It's possible that this will use gcc with some other settings, so that `stdio.h` can be found.

Fourth, there is a brute-force solution, that I'm trying to avoid. You can comment-out lines 33-36 and 42 in `setup.py` and install then. This will give you access to all the MulensModel features, except AC and VBBL. But AC and VBBL are very important - they allow finite-source binary-lens magnifications to be calculated (that's why I try to avoid it).

**Comment by gj272** [comment]
Apologies for the late response. I didn't respond because when trying to fix it myself I have ruined python on my computer unfortunately. 
Yes the Xcode suggestion is the first thing i tried. 
I initially believed the mistake was the difference in pythons(where python install was not thing me to default python but to anaconda3 instead) and where the pointer was taking me hence I tried to use an alias which ruined it all. I now have python2.7 version running via anaconda. 
Now python3 is actually python3 but now my packages are all missing.

**Comment by gj272** [comment]
Here is what pops up when i try it with all versions now. 
gurbirjohal@Gurbirs-MacBook-Air MulensModel-1.14-2.0 % python setup.py install 
Traceback (most recent call last):
  File "setup.py", line 14, in <module>
    files = glob.glob(os.path.join("data", "**", "*"), recursive=True)
TypeError: glob() got an unexpected keyword argument 'recursive'
gurbirjohal@Gurbirs-MacBook-Air MulensModel-1.14-2.0 % which python 
/usr/bin/python
gurbirjohal@Gurbirs-MacBook-Air MulensModel-1.14-2.0 % python2 setup.py install 
Traceback (most recent call last):
  File "setup.py", line 14, in <module>
    files = glob.glob(os.path.join("data", "**", "*"), recursive=True)
TypeError: glob() got an unexpected keyword argument 'recursive'
gurbirjohal@Gurbirs-MacBook-Air MulensModel-1.14-2.0 % python3 setup.py install 
running install
error: can't create or remove files in install directory

The following error occurred while trying to add or remove files in the
installation directory:

    [Errno 2] No such file or directory: '/Library/Python/3.7/site-packages/test-easy-install-78568.write-test'

The installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    /Library/Python/3.7/site-packages/

This directory does not currently exist.  Please create it and try again, or
choose a different installation directory (using the -d or --install-dir
option).

**Comment by rpoleski** [comment]
I'm sorry to hear that. I don't know how the pointer/alias can ruin python. I'm guessing you can remove the alias and just run command like `python3.6` each time, or have an alias that is not something as common as `python`, e.g., `p3.6`. I won't be able to help with bringing back all your packages and settings.

MM is in python3, so trying it in python2 won't work. The support for python2 is getting lower and lower, so I suggest switching to python3. 

You haven't replied if you tried the third option I've proposed above. Even if the make commands don't work there is a way to make all the other parts of MM working - just add MM to your `PYTHONPATH`. You will be getting warnings that VBBL and AC were not important, but all the other parts of the code should work.

**Comment by gj272** [comment]
Yes I was using python 3 then I thought the issues were due to this sort of
thing, so my issue is non mulensmodel related when previously it wasn’t.
Due to the new issues I haven’t been able to try 3. When I restore my
python back up I will check if it works and will get back to you when my
package related issues are sorted!
Thank you for the help.
Regards,
Gurbir
