### ISSUE TITLE
Just a doubt about how the magnification is calculated

### ISSUE THREAD

**Issue by josepereirasn** [rpoleski/MulensModel#96]
In the article " Modeling microlensing events with MulensModel " do you mentioned about cublic spline interpolation is used to find the magnification value togheter with the precomputed methods. 

Can we have more detail about how is this model interpolated? Especially the Witt & Mao (94) expression. That is some article or something like that that could guide us.

**Comment by rpoleski** [comment]
This part of the article is about events that single-lens and single-source with finite source effect. Please have a look at the `source/MulensModel/pointlens.py` file. The interpolation is done there using the scipy functions. The same file has functions that allow direct (i.e., without interpolation) calculation of the magnification, but they are much slower.

**Comment by rpoleski** [comment]
@josepereirasn - I don't see more questions, hence, closing.
